goverment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include(('portal.urls', 'portal'), namespace='portal')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import  GPRegister, S2Regsiter, ObservarRegsiter, CEORegister
urlpatterns = [
    # Home View
    path('', views.home, name="home"),
    path('dashboard/',views.index, name="index"),
    path('observar/',views.observar, name="observar"),
    # Ajax Views
    path('load-taluka/', views.load_taluka, name="ajax_taluka"),
    path('load-panchayat', views.load_panchayat,name="ajax_panchayat"),

    # Signup Views
    path('accounts/signup/gp/', GPRegister.as_view(), name="gp"),
    path('accounts/signup/s2/', S2Regsiter.as_view(), name="accountant"),
    path('accounts/signup/ceo/', CEORegister.as_view(), name="CEO"),
    path('accounts/signup/ob/', ObservarRegsiter.as_view(), name="ob"),

    # Confirmation, Pending, Approved, Payment Views
    path('confim-one/', views.confirm1, name="confirm1"),
    path('pay-one/', views.payment1, name="pay1"),
    path('pay-pending-for-pay-one/', views.pending1, name="pending1"),
    path('confirm-two/', views.confirm2, name="confirm2"),
    path('confirm-three/', views.confirm3, name="confirm3"),
    path('pay-two/', views.payment2, name="pay2"),
    path('pay-three/', views.payment3, name="pay3"),
    path('pay-four/', views.payment4, name="pay4"),
    path('pay-pending-for-pay-two/', views.pending2, name="pending2"),
    path('pay-pending-for-pay-three/', views.pending3, name="pending3"),
    path('confim-four/', views.confirm4, name="confirm4"), 
    path('pay-pending-for-pay-four/', views.pending4, name="pending4"),
    path('audit-msg/', views.audit_msg, name="audit_msg"),

    #s2 views
    path('my-dashboard/', views.s2dashboard, name="s2dashboard"),
    path('confirm-payment/<int:pay_id>/<int:user_id>/', views.confirm_payment, name="confirm_payment"),
    path("utr-missed/", views.utr_missed, name="utr_missed"),
    path("utr-matched/", views.utr_matched, name="utr_matched"),
    path('utr-change/<int:id>/', views.utr_change, name="utr_change"),
    path("utr-missed-two/", views.utr_missedtwo, name="utr_missedtwo"),
    path('utr-change-two/<int:id>/', views.utr_changetwo, name="utr_changetwo"),
    path('audit-approve/<int:id>/', views.audit_approve, name="audit-approve"),
    path('audit-miss-three/', views.audit_miss, name="audit_miss"),
    path('audit-miss-four/', views.audit_miss_four, name="audit_miss_four"),
    path('utr-change-three/<int:id>/', views.utr_changethree, name="utr_changethree"),
    path('audit-edit/<int:id>/', views.audit_edit, name="audit-edit"),
    path('utr-missed-three/', views.utr_missedthree, name="utr_missedthree"),
    path('utr-change-four/<int:id>/', views.utr_changefour, name="utr_changefour"),
    path('utr-missed-four/', views.utr_missedfour, name="utr_missedfour"),
    path('audit-edit-four/<int:id>/', views.audit_edit_four, name="audit-edit-four"),
    path('local/', views.local, name="local"),
    path('ceo-dashboard/', views.ceodashboard, name="ceodashboard"),
    path('approve-ceo/<int:id>/', views.approve_ceo, name="approve-ceo"),
    # Servelence urls
    path('servilence/', views.servilence_dashboard, name="servilence_dashboard"),
    path('servilence-pay-two/', views.servilance2_pay, name="servilance2_pay"),
    path('servilence-pay-one/', views.servilance1_pay, name="servilance1_pay"),
    path('servilence-pay-three/', views.servilance3_pay, name="servilance3_pay"),

    path('servilence-pending-one/', views.servi_pending1, name="servi_pending1"),
    path('servilence-pending-two/', views.servi_pending2, name="servi_pending2"),
    path('servilence-pending-three/', views.servi_pending3, name="servi_pending3"),
    path('servilence-one-missed/', views.servi_miss_one, name="servi_miss_one"),
    path('servilence-two-missed/', views.servi_miss_two, name="servi_miss_two"),
    path('servilence-three-missed/', views.servi_miss_three, name="servi_miss_three"),
    path('servilence-edit-utr/<int:id>/', views.servi_utr_edit, name="servi_utr_edit"),
    path('servilence-edit-utr-two/<int:id>/', views.servi_utr_edit_two, name="servi_utr_edit_two"),
    path('servilence-edit-utr-three/<int:id>/', views.servi_utr_edit_three, name="servi_utr_edit_three"),
    path('confirm-servi-pay/<int:user_id>/<int:pay_id>/', views.servi_pay_confirm, name="servi_pay_confirm"),
    path("upload-doc/", views.upload_doc, name="upload_doc"),
    path("upload-doc-two/", views.upload_doc_two, name="upload_doc_two"),
    path("upload-doc-three/", views.upload_doc_three, name="upload_doc_three"),
    path('audit-approve-serve/<int:audit_id>/', views.ser_audit_approve, name="ser_audit_approve"),
    path('audit-edit-serve/<int:aud_id>/', views.ser_audit_edit, name="ser_audit_edit"),
    path('servi-audit-miss/', views.servi_audit_miss, name="servi_audit_miss"),
    path('servi-audit-miss-two/', views.servi_audit_miss_two, name="servi_audit_miss_two"),
    path('servi-audit-miss-three/', views.servi_audit_miss_three, name="servi_audit_miss_three"),
    path('servi-audit-miss-two-edit/<int:aud_id>/', views.ser_audit_edit_two, name="ser_audit_edit_two"),
     path('servi-audit-miss-three-edit/<int:aud_id>/', views.ser_audit_edit_three, name="ser_audit_edit_three")
]

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, EmailValidator, validate_slug, URLValidator

# Create your models here.
''' Global decleration '''
PAYMENT_STATUS = [
    ('pending' , 'Pending'),
    ('matched' , 'Matched'),
    ('unmatched' , 'Unmatched')
]
DESIGNATION = [
    ('gram_sevak', 'Gram Sevak'),
    ('gram_vikas_adhikari', 'Gram Vikas Adhikari'),
]
''' Abstract User creation '''
class User(AbstractUser):
    is_gp = models.BooleanField(default=False)
    is_observar = models.BooleanField(default=False)
    is_s2 = models.BooleanField(default=False)
    is_ceo = models.BooleanField(default=False)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return str(self.id)

class Grampanchayat(models.Model):
    user = models.OneToOneField("User", primary_key=True, verbose_name="GP", on_delete=models.CASCADE)
    first_name = models.CharField( max_length=100)
    last_name = models.CharField( max_length=100)
    district = models.ForeignKey('District', on_delete=models.CASCADE)
    taluka = models.ForeignKey('Taluka', on_delete=models.CASCADE)
    panchayat = models.ForeignKey('Panchayat', on_delete=models.CASCADE)
    designation = models.CharField( choices=DESIGNATION, max_length=200, )
    phone_regex = RegexValidator(regex=r'^\d{10,10}$', message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=12, blank=True)
    date = models.DateTimeField(auto_now=True)
    email =  models.EmailField(max_length=254, validators=[EmailValidator], unique=True)
    username = models.TextField()

    class Meta:
        verbose_name = "Grampanchayat"
        verbose_name_plural = "Grampanchayats"

    def __str__(self):
        return str(self.first_name + self.last_name)

class Observar(models.Model):
    user = models.OneToOneField("User", primary_key=True, verbose_name="observar", on_delete=models.CASCADE)
    first_name = models.CharField( max_length=100)
    last_name = models.CharField( max_length=100)
    date = models.DateTimeField(auto_now=True)
    username = models.TextField()
    
    class Meta:
        verbose_name = "Observar"
        verbose_name_plural = "Observars"

    def __str__(self):
        return str(self.first_name + self.last_name)

class CEO(models.Model):
    user = models.OneToOneField("User", primary_key=True, verbose_name="CEO", on_delete=models.CASCADE)
    first_name = models.CharField( max_length=100)
    last_name = models.CharField( max_length=100)
    date = models.DateTimeField(auto_now=True)
    username = models.TextField()
    
    class Meta:
        verbose_name = "CEO"
        verbose_name_plural = "CEO"

    def __str__(self):
        return str(self.first_name + self.last_name)

class S2(models.Model):
    user = models.OneToOneField("User", primary_key=True, verbose_name="account", on_delete=models.CASCADE)
    first_name = models.CharField( max_length=100)
    last_name = models.CharField( max_length=100)
    date = models.DateTimeField(auto_now=True)
    username = models.TextField(default="ac")

    class Meta:
        verbose_name = "S2"
        verbose_name_plural = "S2S"

    def __str__(self):
        return str(self.first_name + self.last_name)

''' Chained models '''
class District(models.Model):
    district = models.CharField(max_length=1000)
    date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return str(self.district)

class Taluka(models.Model):
    district = models.ForeignKey('District', on_delete=models.CASCADE)
    taluka = models.CharField(max_length=1000)
    date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return str(self.taluka)

class Panchayat(models.Model):
    taluka = models.ForeignKey('Taluka', on_delete=models.CASCADE)
    panchayat = models.CharField(max_length=1000)
    date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return str(self.panchayat)

''' Normal Models'''
class Confirmation(models.Model):
    date = models.DateTimeField(auto_now=True)
    phaseno = models.PositiveSmallIntegerField(default=1)
    yes_no = models.BooleanField(default=False)
    user = models.ManyToManyField("Grampanchayat", verbose_name="Grampanchayat Confirmation")

    class Meta:
        verbose_name = "Confirmation"
        verbose_name_plural = "Confirmations"

    def __str__(self):
        return str(self.id)

class Payment(models.Model):
    user = models.ManyToManyField("Grampanchayat", verbose_name="Grampanchayat Payment")
    date = models.DateTimeField( auto_now=True)
    utrno = models.PositiveIntegerField()
    phaseno = models.PositiveSmallIntegerField(default=1)
    remark = models.CharField(max_length=500)
    status = models.CharField(choices=PAYMENT_STATUS, max_length=1000,default="pending")

    class Meta:
        verbose_name = "Payment"
        verbose_name_plural = "Payments"

    def __str__(self):
        return str(self.id)

class Audit(models.Model):
    user = models.ManyToManyField("Grampanchayat", verbose_name="Grampanchayat Audit")
    date = models.DateTimeField( auto_now=True)
    document = models.FileField(upload_to="document/", max_length=100)
    phaseno = models.PositiveSmallIntegerField()
    status = models.CharField(choices=PAYMENT_STATUS, max_length=1000,default="pending")

    class Meta:
        verbose_name = "Audit"
        verbose_name_plural = "Audits"

    def __str__(self):
        return str(self.id)

class ServilenceAudit(models.Model):
    user = models.ManyToManyField("Grampanchayat", verbose_name="Grampanchayat Servilence")
    date = models.DateTimeField( auto_now=True)
    document = models.FileField(upload_to="document/", max_length=100)
    phoseno = models.PositiveSmallIntegerField()
    status = models.CharField(choices=PAYMENT_STATUS, max_length=1000,default="pending")
    class Meta:
        verbose_name = "ServilenceAudit"
        verbose_name_plural = "ServilenceAudits"

    def __str__(self):
        return str(self.id)

class ServilencePayment(models.Model):
    user = models.ManyToManyField("Grampanchayat", verbose_name="Grampanchayat ServilencePayment")
    date = models.DateTimeField( auto_now=True)
    phaseno = models.PositiveSmallIntegerField()
    utrno = models.PositiveIntegerField()
    remark = models.CharField(max_length=500,default="None")
    status = models.CharField(choices=PAYMENT_STATUS, max_length=1000,default="pending")
    class Meta:
        verbose_name = "ServilencePayment"
        verbose_name_plural = "ServilencePayments"

    def __str__(self):
        return str(self.id)

class Agency(models.Model):
    user = models.ForeignKey("User", verbose_name="user_agency", on_delete=models.CASCADE)
    choose_goverment = models.BooleanField(default=False)
    choose_local = models.BooleanField(default=False)
    already_certified = models.BooleanField(default=False)
    date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return str(self.choose_goverment) + ' ' + str(self.choose_local)

class PrivateAgency(models.Model):
    user = models.OneToOneField("Grampanchayat", verbose_name="user_agency_data", on_delete=models.CASCADE)
    agency_name = models.CharField( max_length=500)
    cost = models.PositiveIntegerField()
    cert_cost = models.PositiveIntegerField()
    address = models.CharField( max_length=5000)
    phone_regex = RegexValidator(regex=r'^\d{10,10}$', message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=12, blank=True)
    doc = models.FileField( upload_to="document/", max_length=100)
    date = models.DateTimeField( auto_now=True)
    email = models.EmailField( max_length=254)
    status = models.CharField(choices=PAYMENT_STATUS, max_length=1000,default="pending")
    class Meta:
        verbose_name = "PrivateAgency"
        verbose_name_plural = "PrivateAgencys"

    def __str__(self):
        return str(self.agency_name)

portal/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}{% endblock css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
      <header>
        <div class="container">
            <h1>
                <a href="{% url 'portal:home' %}">
                    <img class="img-fluid" src="{% static 'img/logo.png' %}" alt="head-logo">
                </a>
            </h1>
            <p class="head">Government of Maharashtra</p>
            {% if request.user.is_authenticated %}
              <div class="name-log">
                <a href="{% url 'logout' %}">Logout</a>
              </div>
            {% endif %}
        </div>
    </header>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <footer>
    </footer>
   {% block javascript %}
   {% endblock javascript %}
  </body>
</html>

portal/templates/dashboard.html
{% extends './base.html' %}
{% block title %}Dashboard | Government of Maharashtra{% endblock title %}
{% block content %}
    {% load static %}
    <div class="container">
        <div class="outer">
            <h2>आम्ही आपले स्वागत करतो.</h2>
            {% if request.user.is_gp %}
              <h3 class="selection">आपली एजन्सी निवडा</h3>
              <div class="agency-selection home"> 
                  <ul class="ul">
                      <li class="lists">
                          <a data-toggle="modal" data-target="#gov_agency">
                              <h5>सरकारी नियुक्ती एजन्सी</h5>
                              <p class="pos-rel">जर नेमणूक केली असेल तर आपणास शासकीय नियुक्त एजन्सीसमवेत जावे लागेल, एकदा खात्री झाल्यावर निवड पूर्ववत केली जाऊ शकत नाही. </p>
                          </a>
                      </li>
                      <li class="lists">
                          <a data-toggle="modal" data-target="#local_agency">
                              <h5>इतर एजन्सी</h5>
                              <p class="pos-rel">जर नेमणूक केली असेल तर आपण स्थानिक किंवा सार्वजनिक प्रशिक्षण संस्थांसह जाण्याचे निवडत आहात.</p>
                          </a>
                      </li>
                      <li class="lists">
                          <a data-toggle="modal" data-target="#audit">
                              <h5>आपण आधीपासूनच आयएसओ प्रमाणित आहात</h5>
                              <p class="pos-rel">होय असल्यास, यावर क्लिक करा आणि सबमिट करा, आपले ऑडिट करण्यासाठी आपल्याला पुनर्निर्देशित केले जाईल.</p>
                          </a>
                      </li>
                  </ul>
              </div>
            {% elif request.user.is_s2%}
              <h4>Click on below link.</h4>
              <a class="dash" href="{% url 'portal:s2dashboard' %}">Dashboard</a>
            {% elif request.user.is_observar %}
              <h4>Click on below link.</h4>
              <a class="dash" href="{% url 'portal:observar' %}">Dashboard</a>
              {% elif request.user.is_ceo %}
              <h4>Click on below link.</h4>
              <a class="dash" href="{% url 'portal:ceodashboard' %}">Dashboard</a>
            {% endif %}
        </div>
    </div>

<!-- Goverment Agency Modal -->
<div class="modal fade" id="gov_agency" tabindex="-1" role="dialog" aria-labelledby="gov_agencyLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="gov_agencyLabel">You Appointed</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4>सरकारी एजन्सी</h4>
        <div class="des pos-rel">
           आपण सरकारी नियुक्त एजन्सीसमवेत जात आहात, एकदा खात्री झाल्यावर निवड पूर्ववत केली जाऊ शकत नाही.. 
        </div>
      </div>
      <div class="modal-footer">
        <form method="POST">
          {% csrf_token %}
          <div class="choose">
            {{ gov_choose.choose_goverment }}
            <span>{{ gov_choose.choose_goverment.label }}</span>
          </div>
          <button type="submit" name="goverment" id="goverment"class="btn btn-primary">Confirm</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- Local Modal -->
<div class="modal fade" id="local_agency" tabindex="-1" role="dialog" aria-labelledby="local_agencyLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="local_agencyLabel">You Appointed</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4>इतर एजन्सी</h4>
        <div class="des pos-rel">
            आपण स्थानिक एजन्सीसमवेत जात आहात.
        </div>
      </div>
      <div class="modal-footer">
      <form method="POST">
          {% csrf_token %}
          <div class="choose">
            {{ pub_form.choose_local }}
            <span>{{ pub_form.choose_local.label }}</span>
          </div>
          <button type="submit" name="public" id="public" class="btn btn-primary">Confirm</button>
        </form>
          </div>
    </div>
  </div>
</div>
<!-- ALready Certified Modal -->
<div class="modal fade" id="audit" tabindex="-1" role="dialog" aria-labelledby="auditLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="local_agencyLabel">आपण नियुक्त</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4>इतर एजन्सी</h4>
        <div class="des pos-rel">
           सबमिट करून आपण म्हणत आहात की आपल्याकडे आयएसओ प्रमाणित आहे.
        </div>
      </div>
      <div class="modal-footer">
      <form method="POST">
          {% csrf_token %}
          <div class="choose">
            {{ certified.already_certified }}{{ certified.already_certified.label }}
            <span></span>
          </div>
          <button type="submit" name="certified" id="certified"class="btn btn-primary">Confirm</button>
          {% comment %} <a type="submit" name="public" id="public" href="{% url 'portal:servilance' %}" class="btn btn-primary">Confirm</a> {% endcomment %}
        </form>
          </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock  %}

portal/templates/index.html
{% extends './base.html' %}
{% block css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.css">
{% endblock css %}
{% block content %}
{% load static %}
<div class="container">
        <div class="outer">
            <h3 class="selection">Your Progress yet</h3>
            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">

            {% comment %} Agency {% endcomment %}
            <li class="nav-item ">
              <a class="nav-link active" id="pills-agency-tab" data-toggle="pill" href="#pills-agency" role="tab" aria-controls="pills-agency" aria-selected="false">Agency</a>
            </li>

            {% comment %} Payment {% endcomment %}
            <li class="nav-item">
              <a class="nav-link " id="pills-payment-tab" data-toggle="pill" href="#pills-payment" role="tab" aria-controls="pills-payment" aria-selected="true">Payment</a>
            </li>
           
            {% comment %} Phase {% endcomment %}
            <li class="nav-item">
              <a class="nav-link " id="pills-phase-tab" data-toggle="pill" href="#pills-phase" role="tab" aria-controls="pills-phase" aria-selected="true">Phase</a>
            </li>
             {% comment %} Audit {% endcomment %}
            <li class="nav-item">
              <a class="nav-link {% if not phasefourpay %}disabled
              {% endif %}" id="pills-audit-tab" data-toggle="pill" href="#pills-audit" role="tab" aria-controls="pills-audit" aria-selected="false">Audit</a>
            </li>
            
          </ul>
          <div class="tab-content" id="pills-tabContent">
             <div class="tab-pane fade show active" id="pills-agency" role="tabpanel" aria-labelledby="pills-agency-tab">
              आपण सरकारी निवडलेली एजन्सी निवडली आहे
             </div>
              <div class="tab-pane fade" id="pills-payment" role="tabpanel" aria-labelledby="pills-payment-tab">
                आपण आगाऊ देय दिले आहे आणि ते मंजूर केले आहे.
              </div>
              <div class="tab-pane fade" id="pills-phase" role="tabpanel" aria-labelledby="pills-phase-tab">
                <table data-toggle="table" data-custom-sort="customSort" data-pagination="true" data-search="true">
                  <thead>
                    <tr>
                      <th scope="col" data-sortable="true">Step 1</th>
                      <th scope="col" data-sortable="true">Step 2</th>
                      <th scope="col" data-sortable="true">Step 3</th>
                      <th scope="col" data-sortable="true">Step 4</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>पूर्ण</td>
                      <td>
                        {% if phasetwopay %}
                            पूर्ण
                        {% else %}
                      अनिर्णित
                          <a class="pay" href="{% url 'portal:confirm2' %}">Go to Step Two</a>
                        {% endif %}</td>
                      <td>
                        {% if phasethreepay %}
                          पूर्ण
                          {% elif phasetwopay %}
                          अनिर्णित
                          <a class="pay" href="{% url 'portal:confirm3' %}">Go to Step Three</a>
                        {% else %}
                          अनिर्णित
                        {% endif %} </td>
                      <td>
                        {% if phasefourpay %}
                          पूर्ण
                        {% elif phasethreepay %}
                          अनिर्णित
                          <a class="pay" href="{% url 'portal:confirm4' %}">Go to Step Four</a>
                        {% else %}
                        अनिर्णित
                        {% endif %}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              
              <div class="tab-pane fade" id="pills-audit" role="tabpanel" aria-labelledby="pills-audit-tab">
                 <img class="img-fluid" src="{% static '/img/green_circle_tick.png' %}">
                  <p>Your all steps are completed, now lets move to servilence audit. click below to go to first audit.</p>
                  <a type="button" class="btn btn-light" href="{% url 'portal:servilence_dashboard' %}">Dashboard</a>
              </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js"></script>
{% endblock javascript %}