goverment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include(('portal.urls', 'portal'), namespace='portal')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import  GPRegister, S2Regsiter, ObservarRegsiter, CEORegister
urlpatterns = [
    # Home View
    path('', views.home, name="home"),
    path('dashboard/',views.index, name="index"),
    path('observar/',views.observar, name="observar"),
    # Ajax Views
    path('load-taluka/', views.load_taluka, name="ajax_taluka"),
    path('load-panchayat', views.load_panchayat,name="ajax_panchayat"),

    # Signup Views
    path('accounts/signup/gp/', GPRegister.as_view(), name="gp"),
    path('accounts/signup/s2/', S2Regsiter.as_view(), name="accountant"),
    path('accounts/signup/ceo/', CEORegister.as_view(), name="CEO"),
    path('accounts/signup/ob/', ObservarRegsiter.as_view(), name="ob"),

    # Confirmation, Pending, Approved, Payment Views
    path('confim-one/', views.confirm1, name="confirm1"),
    path('pay-one/', views.payment1, name="pay1"),
    path('pay-pending-for-pay-one/', views.pending1, name="pending1"),
    path('confirm-two/', views.confirm2, name="confirm2"),
    path('confirm-three/', views.confirm3, name="confirm3"),
    path('pay-two/', views.payment2, name="pay2"),
    path('pay-three/', views.payment3, name="pay3"),
    path('pay-four/', views.payment4, name="pay4"),
    path('pay-pending-for-pay-two/', views.pending2, name="pending2"),
    path('pay-pending-for-pay-three/', views.pending3, name="pending3"),
    path('confim-four/', views.confirm4, name="confirm4"), 
    path('pay-pending-for-pay-four/', views.pending4, name="pending4"),
    path('audit-msg/', views.audit_msg, name="audit_msg"),

    #s2 views
    path('my-dashboard/', views.s2dashboard, name="s2dashboard"),
    path('confirm-payment/<int:pay_id>/<int:user_id>/', views.confirm_payment, name="confirm_payment"),
    path("utr-missed/", views.utr_missed, name="utr_missed"),
    path("utr-matched/", views.utr_matched, name="utr_matched"),
    path('utr-change/<int:id>/', views.utr_change, name="utr_change"),
    path("utr-missed-two/", views.utr_missedtwo, name="utr_missedtwo"),
    path('utr-change-two/<int:id>/', views.utr_changetwo, name="utr_changetwo"),
    path('audit-approve/<int:id>/', views.audit_approve, name="audit-approve"),
    path('audit-miss-three/', views.audit_miss, name="audit_miss"),
    path('audit-miss-four/', views.audit_miss_four, name="audit_miss_four"),
    path('utr-change-three/<int:id>/', views.utr_changethree, name="utr_changethree"),
    path('audit-edit/<int:id>/', views.audit_edit, name="audit-edit"),
    path('utr-missed-three/', views.utr_missedthree, name="utr_missedthree"),
    path('utr-change-four/<int:id>/', views.utr_changefour, name="utr_changefour"),
    path('utr-missed-four/', views.utr_missedfour, name="utr_missedfour"),
    path('audit-edit-four/<int:id>/', views.audit_edit_four, name="audit-edit-four"),
    path('local/', views.local, name="local"),
    path('ceo-dashboard/', views.ceodashboard, name="ceodashboard"),
    path('approve-ceo/<int:id>/', views.approve_ceo, name="approve-ceo"),
    # Servelence urls
    path('servilence/', views.servilence_dashboard, name="servilence_dashboard"),
    path('servilence-pay-two/', views.servilance2_pay, name="servilance2_pay"),
    path('servilence-pay-one/', views.servilance1_pay, name="servilance1_pay"),
    path('servilence-pay-three/', views.servilance3_pay, name="servilance3_pay"),

    path('servilence-pending-one/', views.servi_pending1, name="servi_pending1"),
    path('servilence-pending-two/', views.servi_pending2, name="servi_pending2"),
    path('servilence-pending-three/', views.servi_pending3, name="servi_pending3"),
    path('servilence-one-missed/', views.servi_miss_one, name="servi_miss_one"),
    path('servilence-two-missed/', views.servi_miss_two, name="servi_miss_two"),
    path('servilence-three-missed/', views.servi_miss_three, name="servi_miss_three"),
    path('servilence-edit-utr/<int:id>/', views.servi_utr_edit, name="servi_utr_edit"),
    path('servilence-edit-utr-two/<int:id>/', views.servi_utr_edit_two, name="servi_utr_edit_two"),
    path('servilence-edit-utr-three/<int:id>/', views.servi_utr_edit_three, name="servi_utr_edit_three"),
    path('confirm-servi-pay/<int:user_id>/<int:pay_id>/', views.servi_pay_confirm, name="servi_pay_confirm"),
    path("upload-doc/", views.upload_doc, name="upload_doc"),
    path("upload-doc-two/", views.upload_doc_two, name="upload_doc_two"),
    path("upload-doc-three/", views.upload_doc_three, name="upload_doc_three"),
    path('audit-approve-serve/<int:audit_id>/', views.ser_audit_approve, name="ser_audit_approve"),
    path('audit-edit-serve/<int:aud_id>/', views.ser_audit_edit, name="ser_audit_edit"),
    path('servi-audit-miss/', views.servi_audit_miss, name="servi_audit_miss"),
    path('servi-audit-miss-two/', views.servi_audit_miss_two, name="servi_audit_miss_two"),
    path('servi-audit-miss-three/', views.servi_audit_miss_three, name="servi_audit_miss_three"),
    path('servi-audit-miss-two-edit/<int:aud_id>/', views.ser_audit_edit_two, name="ser_audit_edit_two"),
     path('servi-audit-miss-three-edit/<int:aud_id>/', views.ser_audit_edit_three, name="ser_audit_edit_three")
]

portal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView
from .models import User, Taluka, Panchayat, Agency, Confirmation, Payment, Grampanchayat, Audit, PrivateAgency, ServilencePayment,ServilenceAudit
from .forms import GPSignUPForm, CEOSignUpForm, S2SignUpForm, ObservarSignUpForm, PublicForm, GovermentForm, CertifiedForm, ConfirmationForm, PaymentForm, PaymentApproveForm, UTRapproveForm, AuditForm, AuditSelectForm, AuditEditForm, PrivateAgencyForm, CEOApproveForm, ServilencePaymentForm, ServilenceAuditForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from goverment import settings


# Create your views here.

'''Deafult Home View'''
@login_required
def home(request):
    confirmtwo, paytwo, confirmthree, paythree, auditthree, auditfour, confirmfour,payfour, payone = '', '','','','', '','','',''
    get_certified_selected_agency, ser_audit, servilencepayment, servilencepayment_two, ser_audit_two, servilencepayment_three, ser_audit_three = '', '', '', '', '','', ''
    try:
        get_gov_selected_agency = Agency.objects.filter (user = request.user.id, choose_goverment='True')
        confirmone = Confirmation.objects.filter(user=request.user.id, phaseno__iexact=1)
        payone = Payment.objects.get(user=request.user.id, phaseno=1)
        confirmtwo = Confirmation.objects.filter(user=request.user.id, phaseno__iexact=2)
        paytwo = Payment.objects.get(user=request.user.id, phaseno=2)
        confirmthree = Confirmation.objects.filter(user=request.user.id, phaseno__iexact=3)
        paythree = Payment.objects.get(user=request.user.id, phaseno=3)
        auditthree = Audit.objects.get(user=request.user.id, phaseno=3)
        auditfour = Audit.objects.get(user=request.user.id, phaseno=4)
        confirmfour = Confirmation.objects.filter(user=request.user.id, phaseno__iexact=4)
        payfour = Payment.objects.get(user=request.user.id, phaseno=4)
        get_certified_selected_agency = Agency.objects.filter (user = request.user.id, already_certified='True')
        servilencepayment = ServilencePayment.objects.get(user=request.user.id, phaseno=1)
        ser_audit = ServilenceAudit.objects.get(user=request.user.id, phoseno=1)
        servilencepayment_two = ServilencePayment.objects.get(user=request.user.id, phaseno=2)
        ser_audit_two = ServilenceAudit.objects.get(user=request.user.id, phoseno=2)
        servilencepayment_three = ServilencePayment.objects.get(user=request.user.id, phaseno=3)
        ser_audit_three = ServilenceAudit.objects.get(user=request.user.id, phoseno=3)
    except:
        pass 
    if request.user.is_gp:
        if get_gov_selected_agency:
            if confirmone:
                if payone:
                    if payone.status == "unmatched":
                        return redirect("portal:utr_missed")
                    elif payone.status == "matched":
                        if confirmtwo:
                            if paytwo:
                                if paytwo.status == "unmatched":
                                    return redirect("portal:utr_missedtwo")
                                elif paytwo.status == "matched":
                                    if confirmthree:
                                        if paythree:
                                            if paythree.status =="unmatched":
                                                return redirect("portal:utr_missedthree")
                                            elif paythree.status =="matched":
                                                if auditthree.status =="unmatched":
                                                    return redirect("portal:audit_miss")
                                                elif auditthree.status =="matched":
                                                    if confirmfour:
                                                        if payfour:
                                                            if payfour.status =="unmatched":
                                                                return redirect("portal:utr_missedfour")
                                                            elif payfour.status =="matched":
                                                                if auditfour.status =="unmatched":
                                                                    return redirect("portal:audit_miss_four")
                                                                elif auditfour.status =="matched":
                                                                    if servilencepayment:
                                                                        if servilencepayment.status == "unmatched":
                                                                            return redirect("portal:servi_miss_one")
                                                                        elif servilencepayment.status == "matched":
                                                                            if ser_audit:
                                                                                if ser_audit.status=="unmatched":
                                                                                    return redirect("portal:servi_audit_miss")
                                                                                elif ser_audit.status =='matched':
                                                                                    if servilencepayment_two:
                                                                                        if servilencepayment_two.status == "unmatched":
                                                                                            return redirect("portal:servi_miss_two")
                                                                                        elif servilencepayment_two.status == "matched":
                                                                                            if ser_audit_two:
                                                                                                if ser_audit_two.status=="unmatched":
                                                                                                    return redirect("portal:servi_audit_miss_two")
                                                                                                elif ser_audit_two.status =='matched':
                                                                                                    if servilencepayment_three:
                                                                                                        if servilencepayment_three.status == "unmatched":
                                                                                                            return redirect("portal:servi_miss_three")
                                                                                                        elif servilencepayment_three.status == "matched":
                                                                                                            if ser_audit_three:
                                                                                                                if ser_audit_three.status=="unmatched":
                                                                                                                    return redirect("portal:servi_audit_miss_three")
                                                                                                                elif ser_audit_three.status =='matched':
                                                                                                                    return redirect('portal:servilence_dashboard')
                                                                                                                return redirect("portal:servi_pending3")
                                                                                                            return redirect("portal:upload_doc_three")
                                                                                                        return redirect("portal:servi_pending3")
                                                                                                    return redirect('portal:servilence_dashboard')
                                                                                                return redirect("portal:servi_pending2")
                                                                                            return redirect("portal:upload_doc_two")
                                                                                        return redirect("portal:servi_pending2")
                                                                                    return redirect('portal:servilence_dashboard')
                                                                                return redirect("portal:servi_pending1")
                                                                            return redirect("portal:upload_doc")
                                                                        return redirect("portal:servi_pending1")
                                                                    return redirect("portal:servilence_dashboard")
                                                                return redirect("portal:audit_msg")
                                                            return redirect("portal:pending4")
                                                        return redirect("portal:pay4")
                                                    return redirect("portal:index")

portal/templates/UTR/pay-cofirm.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
        <h3 class="selection">पैसे भरले</h3>
        <h3 class="selection">  Payment Approval Status From S2 Infotech International Limited</h3>
        <img class="img-fluid" src="{% static '/img/green_circle_tick.png' %}">
        <a type="button" class="btn btn-light" href="{% url 'portal:index' %}">Go to dashboard</a>
        </div>
    </div>
{% endblock content %}

portal/templates/UTR/utr-change.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
            <h3 class="selection">स्टेज पेमेंट change</h3>
            <div class="agency-selection">
                <ul class="ul">
                    <li class="payments"> 
                        <div class="row">
                            <div class="col-md-8">
                                <div class="info">
                                    <p class="count">₹ 7788.00 + ₹ 1188<small>18% GST</small> = 8976.00</p>
                                </div>
                                <p>Remark</p>
                                <p class="mismatched">{{paymiss.remark}}.</p>
                            </div>
                            <div class="col-md-4">
                                <p>खाली इनपुट फील्डमध्ये आपली आरटीजीएस संख्या प्रविष्ट करा</p>
                                <form method="POST">
                                    {% csrf_token %}
                                    {{utrform.utr}}
                                    <button type="submit" class="sel-rtgs pay" disabled="disabled">Submit</button>
                                </form>
                            </div>
                        </div>
                        {% comment %} <a href="{% url 'portal:pays' %}" type="button" class="btn btn-primary">Submit</a> {% endcomment %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
    <script src="{% static 'js/jquery.min.js' %}"></script>    
    <script src="{% static 'js/main.js' %}"></script>

{% endblock javascript %}

portal/templates/UTR/utr-changefour.html
{% extends '../base.html' %}
{% block content %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
            <h3 class="selection">स्टेज पेमेंट change</h3>
            <div class="agency-selection">
                <ul class="ul">
                    <li class="payments"> 
                        <div class="row">
                            <div class="col-md-8">
                                <div class="info">
                                    <p class="count">₹ 7788.00 + ₹ 1188<small>18% GST</small> = 8976.00</p>
                                </div>
                                <p>Remark</p>
                                <p class="mismatched">{{paymiss.remark}}.</p>
                            </div>
                            <div class="col-md-4">
                                <p>खाली इनपुट फील्डमध्ये आपली आरटीजीएस संख्या प्रविष्ट करा</p>
                                <form method="POST">
                                    {% csrf_token %}
                                    {{utrform.utr}}
                                    <button type="submit" class="sel-rtgs pay">Submit</button>
                                </form>
                            </div>
                        </div>
                        {% comment %} <a href="{% url 'portal:pays' %}" type="button" class="btn btn-primary">Submit</a> {% endcomment %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

portal/templates/UTR/utr.html
{% extends '../base.html' %}
{% block content %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
           <div class="info">
                <p>स्टेज {{stage }} पेमेंट </p>
                <p class="count">₹ 7788.00 + ₹ 1188<small>18% GST</small> = 8976.00</p>
            </div>
            <p class="mismatched">यूटीआर क्रमांक जुळला नाही, कृपया यूटीआर तपासा आणि पुन्हा सबमिट करा.</p>
            <h3 class="selection"> Payment Approval Status From S2 Infotech International Limited</h3>
            <button type="button" class="btn btn-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16"><path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/></svg>
            </button>
            <a href="{% url 'portal:utr_change' paymiss.id %}" class="pay">Edit</a>
        </div>
    </div>
{% endblock content %}

portal/templates/UTR/utrfour.html
{% extends '../base.html' %}
{% block content %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
           <div class="info">
                <p>स्टेज {{stage }} पेमेंट </p>
                <p class="count">₹ 7788.00 + ₹ 1188<small>18% GST</small> = 8976.00</p>
            </div>
            <p class="mismatched">यूटीआर क्रमांक जुळला नाही, कृपया यूटीआर तपासा आणि पुन्हा सबमिट करा.</p>
            <h3 class="selection"> Payment Approval Status From S2 Infotech International Limited</h3>
            <button type="button" class="btn btn-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16"><path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/></svg>
            </button>
            <a href="{% url 'portal:utr_changefour' paymiss.id %}" class="pay">Edit</a>
        </div>
    </div>
{% endblock content %}

portal/templates/UTR/utrthree.html
{% extends '../base.html' %}
{% block content %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
           <div class="info">
                <p>स्टेज {{stage }} पेमेंट </p>
                <p class="count">₹ 7788.00 + ₹ 1188<small>18% GST</small> = 8976.00</p>
            </div>
            <p class="mismatched">यूटीआर क्रमांक जुळला नाही, कृपया यूटीआर तपासा आणि पुन्हा सबमिट करा.</p>
            <h3 class="selection"> Payment Approval Status From S2 Infotech International Limited</h3>
            <button type="button" class="btn btn-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16"><path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/></svg>
            </button>
            <a href="{% url 'portal:utr_changethree' paymiss.id %}" class="pay">Edit</a>
        </div>
    </div>
{% endblock content %}

portal/templates/UTR/utrtwo.html
{% extends '../base.html' %}
{% block content %}
    <div class="container">
      <div class="error">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        <div class="outer payments-div">
           <div class="info">
                <p>स्टेज {{stage }} पेमेंट </p>
                <p class="count">₹ 7788.00 + ₹ 1188<small>18% GST</small> = 8976.00</p>
            </div>
            <p class="mismatched">यूटीआर क्रमांक जुळला नाही, कृपया यूटीआर तपासा आणि पुन्हा सबमिट करा.</p>
            <h3 class="selection"> Payment Approval Status From S2 Infotech International Limited</h3>
            <button type="button" class="btn btn-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16"><path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/></svg>
            </button>
            <a href="{% url 'portal:utr_changetwo' paymiss.id %}" class="pay">Edit</a>
        </div>
    </div>
{% endblock content %}